# Assessment package {#assessments}

> For most students, assessment requirements literally define the
> curriculum. [@james_2002_assessinglearningaustralian p. 7]

There are four types of assessment in this course:

+---+--------------------------------------+---------------------------------+-------------+
|   |                                       |                                | Approximate |
|   | Assessment                            | When and where due             | Weighting   |
+---+---------------------------------------+--------------------------------+-------------+
| 1 | [Weekly learning journal (LJ)](#ass1) | 17:00 on Thursday (weeks 1--5) | 25 %        |
|   |                                       | Via canvas                     |             |
+---+---------------------------------------+--------------------------------+-------------+
| 2 | [Peer evaluation of LJs](#ass2)       | 17:00 on Friday (weeks 1--5)   | 15 %        |
|   |                                       | Via canvas                     |             |
+---+---------------------------------------+--------------------------------+-------------+
| 3 | [Summative learning journal](#ass3)   | 17:00 on 1 September           | 50 %        |
|   |                                       | Via canvas                     |             |
+---+---------------------------------------+--------------------------------+-------------+
| 4 | [Participation](#ass4)                | In-class, every class          | 10 %        |
+---+---------------------------------------+--------------------------------+-------------+

All of the assessments are relevant to
the [learning objectives](#learning-objectives).

There is no final examination; all the assessment takes place during
the six weeks of the course.

## Learning objectives

At the completion of this course you should be able to *select*
qualitative research methods that are *appropriate* for your chosen
academic conversation [@huff_2009_designingresearchpublication], and
to *use* those methods in a *proficient* manner.

In other words, by the end of this course it is expected that you will be able
to:

1. select qualitative research methods that are appropriate to the
   research conversation in which the student wishes to participate;
2. be proficient in use tools and techniques to collect qualitative
   data;
4. effectively communicate the findings arising from the collection and
   analysis of qualitative data;
3. be proficient in use tools and techniques to analyse qualitative
   data;
5. describe how the choices they make around the collection, analysis,
   and presentation of qualitative data is congruent with their chosen
   research conversation;
6. evaluate the quality of qualitatively-based research methods; and,
7. employ the tools and techniques of qualitative research methods in
   a manner that is ethical.



## Weekly learning journals {#ass1}

### Task objectives {-}
* To foster self-reflection on (a) the theory presented in the course,
  and (b) your experiences in being both an investigator and a
  participant in qualitative research.
	
* To help with your sense making
  [@weick_1995_sensemakingorganizations] regarding this course.

A casual search using Google Scholar for learning journals provides a
plethora of articles extolling their virtues. Broadly, learning
journals foster high quality self-reflection and increase critical
thinking. 

You are to maintain a weekly learning journal. Later, you are to use
the your weekly journal as the 'data' for
a [summative learning journal](#ass4)/essay on your major learnings
from this course.

### Task overview {-}

For each of the first five weeks of the course you are to write a
learning journal entry of at least 300 words. The more you write the
more grist you will have for your [summative learning journal](#ass4).

In each of your learning journal entries, you are to explore the
linkages between the theoretical content of the course; e.g., the
readings and class sessions with your practical experience e.g., doing
and using qualitative research tools and techniques. As well as
content (theory) from this course, you may, if appropriate, draw on
material from other courses; indeed, you should make linkages to
BUSINESS 710.

Ultimately, you should be considering the real difference the course
is making to your thinking and behaviour.

### What does a good learning journal look like? {-}

Let's begin by looking at the common problems. Based on experience
with previous classes, the main problems are:

* Many journals do not have a logical structure; the approach recommended
  by Daudelin [-@daudelin_1996_learningexperiencereflection], should
  be your model. Using Daudelin's method is the one most significant
  changes that most people could make when trying to improve their
  learning journals.
	
* When using theory in their journals, people often use it to label
  things; e.g., 'Interviews with more than two people are often called
  focus groups'. Very few (if any) people are using theory to either
  explain what is happening, or predict what might happen.
	
* This is closely tied to the focus of some journals (i.e, not
  substantively addressing a real issue). My assumption is that this
  is partly because people aren't drawing on particular theory to
  address a particular problem; instead they are drawing on the
  'theory of the week'. I really encourage you to use Daudeline's
  approach, select theory that supports that issue (and that won't
  necessarily be theory of the week).
	
* Finally, many journals read like a 'stream of conscious', rather
  than a considered (and edited) reflection upon the week's learning
  and writing up that reflection.


## Peer evaluation {#ass2}

### Task objectives {-}

Reflexivity---as distinct from reflection [e.g.,
@hibbert_2010_reflexivityrecursionrelationality]---is an important
characteristic of qualitative research and its researchers [@haynes_2012_reflexivityqualitativeresearch].

* Through evaluating and commenting on the reflections of your peers,
  this assignment seeks to engender greater reflexivity.
  
* To provide developmental feedback on your peers' thinking about their
  stance and approach to qualitative research.

### Task overview {-}

Each week you must review, provide feedback on, and evaluate the
learning journals of two of your colleagues. Over the course you will
write 10 sets of feedback. Your primary goal in providing feedback is to help
the author do a better job next time. If you feedback does not achieve
that, then the author can rightly complain about the quality of your
feedback (and that will affect your marks).

The feedback should, as a minimum, address:

* How well the journal meets the guidelines provided by Daudelin
  [-@daudelin_1996_learningexperiencereflection].
* The extent to which the journal demonstrates achievement in the
  higher levels of Bloom et al.'s
  [-@bloom_1956_taxonomyeducationalobjectives] taxonomy of the
  cognitive domain.
* The quality of the writing. 

In all cases, you should suggest how they might improve their journal;
it is insufficient to point out the weaknesses in their journal
without providing specific actionable ways they might improve. For
example, it is not good enough to say, "Check your grammar". Rather
you explain the nature of the problem and how they might fix it.
Having said that, items like grammar and spelling are 'hygiene'
factors---you should first provide feedback on more material aspects of
journals, and then move on to the smaller matters (if warranted).

That being said, the secondary goal---and a characteristic of the best
reviews--is to foster the development of greater reflexivity in your
peers' and your own approach to qualitative research.

## Summative learning journal {#ass3}

### Task objectives {-}

* Build on the weekly learning journals to enable an integrative 
  reflection of your learning across the whole course.
  
* To demonstrate what you regard as being most important in being a
  qualitative researcher.
  
* To provide a basis for the evaluation of your achievement of the
  course's learning objectives.
  
### Task overview {-}

This final part of the assignment is a summative evaluation of your
weekly journals. Drawing on your weekly journal entries, you are to
write a final, summative journal entry of at least 2,000 words.

Your summative learning journal is quite different to your weekly learning journals.

* It should focus on something that you have learnt throughout the
  course and demonstrate what you can do better now than what you
  could do before the course.
* It must demonstrate the breadth as well as the depth, of what you
  have learnt.
* It should provide good evidence of both evaluation and synthesis
  [@bloom_1956_taxonomyeducationalobjectives].
* It should be based on the 'data' from your weekly learning journals,
  and possible insights you have had as a result of providing feedback
  on others' learning journals; you may also draw on other writing you
  have done for this course..
* It will probably focus on one or two major takeaways/insights. Maybe
  three, certainly not five. These are the things that have changed
  the way you think about qualitative research methods and changed
  your (planned) behaviour.
* The summative journal should not focus on being too personal about
  your experiences throughout the course, but instead focus on how you
  can apply your learning in the future.

You should strive to demonstrate how you meet
the [learning objectives](#learning-objectives) of this course, in the
context of the [postgraduate profile](#profile).

###  General comments on the weekly and summative learning journals {-}

* For many in the class, this is the first time they will have had to
  undertake reflective writing. As a result, some people will
  approach this assignment with some trepidation. For those people,
  the article by Daudelin
  [-@daudelin_1996_learningexperiencereflection] will provide
  assistance. As you progress, you should find writing journals
  increasingly easy and natural. As a result, your later journals may
  be considerably longer than your earlier ones. Because of this,
  there is no upper word limit for your weekly journal entries.
* In your learning journals, it is normal and acceptable to use the
  first person (e.g., I, me, etc.).
* The quality of your writing matters.
* Failing to correctly cite/reference material in your journals can
  incur a 10-percent penalty being applied to your summative learning
  journal. You should correctly cite your weekly learning journal
  using an APA formatted references.
* If it looks like you have 'blown off' doing the weekly learning
  journals it is impossible to get a passing grade for the summative
  learning journals.
* In this context, meaningful feedback means that the recipient can
  unambiguously use it to improve their work within the guidelines
  provided (in the opinion of the recipient, other classmates, or the
  teaching staff). If you feel unhappy about the quality of the
  feedback you receive from your peers, let the teaching staff know.


## Participation {#ass4}

### Task objectives {-}

* To provide an opportunity to practice with the tools and techniques
  of qualitative research.
  
* To gain experience of the consequences of the choice and use of
  differing tools and techniques of qualitative research.

* To better prepare you to ***do*** qualitative research.

### Task overview {-}

I want you to participate so that you can learn from each other. Good
participation is known to increases what is remembered, how well it is
assimilated, and how the learning is used in new situations. Through
participating, you will clarify your own thinking about the content of
the course, and you will provide your peers with the opportunity to
provide constructive feedback, further deepening your understanding of
the material. Likewise, in listening to, and responding to, the
participation of others, you will have the opportunity to demonstrate
alternate ways of interpreting and applying class material. In a
course like this, that stresses the application of material, extensive
participation an essential element of students’ learning and of the
classes success.

### Grading participation {-}
I am a holistic marker, and each class, I will evaluate your
participation using the following guidelines:

* *Outstanding Contributor* (3): Contributions in class reflect
  exceptional preparation. Ideas offered are always substantive, and
  provide one or more major insights as well as direction for the
  class. Challenges are well substantiated and persuasively presented.
  If this person were not a member of the class, the quality of
  discussion would be diminished markedly.

* *Good Contributor* (2): Contributions in class reflect thorough
  preparation. Ideas offered are usually substantive, provide good
  insights, and sometimes direction for the class. Challenges are well
  substantiated and often persuasive. If this person were not a member
  of the class, the quality of discussion would be diminished.

* *Adequate Contributor* (1): Contributions in class reflect satisfactory
  preparation. Ideas offered are sometimes substantive, provide
  generally useful insights but seldom offer a new direction for the
  discussion. Challenges are sometimes presented, fairly well
  substantiated, and are sometimes persuasive. If this person were not
  a member of the class, the quality of discussion would be diminished
  somewhat.

* *Non-Participant* (0): This person says little or nothing in class.
  Hence, there is not an adequate basis for evaluation. If this person
  were not a member of the class, the quality of discussion would not
  be changed.

* *Unsatisfactory Contributor* (-2): Contributions in class reflect
  inadequate preparation. Ideas offered are seldom substantive,
  provide few if any insights, and never a constructive direction for
  the class. Integrative comments and effective challenges are absent.
  If this person were not a member of the class, valuable air-time
  would be saved.

If at the end of the course, the majority of your participation was
scored with a 3, you mark will reflect a grade in the A-range. I.e.,
six 3s or more.

If the majority of your participation was scored as either 3 and 2,
you mark will reflect a grade in the B-range. I.e., six of your
participation scores are 3s or 2s --- more 3s move you more towards a
B+, more 2s move you toward a B-.

Most other combinations of scoring (1s 2s and 3s) will result in a
C-grade. That said, if you only get 1s and 2s you may get a failing
grade.

Note, that each instance of a -2 score for participation effectively
nullifies you highest previous score; it represents a material
penalty.


## Grading criteria

The table below shows the general criteria against which work is
assessed. Although 'grading on the curve' is not used, it is usual
that most students work falls within the B-range.

+-------+-------------------------------------------------------------------------------------+
| Grade | Description                                                                         |
+-------+-------------------------------------------------------------------------------------+
| A+    | Rare, outstanding                                                                   |
+-------+-------------------------------------------------------------------------------------+
| A     | Exceptional and beyond what was expected                                            |
+-------+-------------------------------------------------------------------------------------+
| A-    | Excellent                                                                           |
+-------+-------------------------------------------------------------------------------------+
| B+    | Polished and very good                                                              |
+-------+-------------------------------------------------------------------------------------+
| B     | Covers everything that was expected, comprehensive; demonstrated good understanding |
+-------+-------------------------------------------------------------------------------------+
| B-    | Good coverage but minor flaws                                                       |
+-------+-------------------------------------------------------------------------------------+
| C+    | Demonstrated adequate understanding of fundamentals, but some gaps                  |
+-------+-------------------------------------------------------------------------------------+
| C     | Just adequate, some problems                                                        |
+-------+-------------------------------------------------------------------------------------+
| C-    | Just adequate, many problems                                                        |
+-------+-------------------------------------------------------------------------------------+
| D+    | Inadequate and lack of understanding                                                |
+-------+-------------------------------------------------------------------------------------+
| D     | Very poor                                                                           |
+-------+-------------------------------------------------------------------------------------+


Generally, you should be aware that:

 * Written work is graded for quality of writing, grammar, etc., as
   well as content. This includes your learning journals, summative
   learning journals, and the comments and feedback you give to
   others.
 * APA referencing must be used.
 * In order to be eligible for 100 percent of your course grade, you
   must participate fully and unequivocally in all of the tasks
   associated with this course.
   
Through the assessments you need to demonstrate the depth and the
quality of your learning about doing qualitative research methods.

