# Structure of the course {#course-structure}

## An overview {#course-overview}

### Some mechanics

This course meets twice a week, on Mondays at 13:00, and on Wednesdays
at 10:00 for three hours; but the course only runs for the first six
weeks of the semester. Thus, the average student should expect to
spend 20 hours per week on course related activities. My office is in
room 439, of the Owen G. Glenn Building (260-439), and---during term
time---I have office hours on Wednesday at 15:00. My email address is
`mail@petersmith.org`.

### My assumptions about you

Having completed BUSINESS 710,^[You should have completed some form of
research design course before undertaking this course.] you should
have a sense of the *academic conversation* in which you wish to
participate. This implies that you can locate that discussion in terms
of: the discipline/sub-field to which it belongs; the ontology and
epistemology upon which the conversation is based; the (types) of
theories that are typically used; the journals that are relevant; and
the appropriate methodological position
[@huff_2009_designingresearchpublication p. 7]. Everything else being
equal, your choice of method is a function of your choice of academic
conversation.

Note: You do not need to base your work in this course on the research
proposal you prepared in BUSINESS 710. But you do need to be clear as
to the  conversation to which you want to participate.

My second assumption is that---sooner or later in your academic
career---you will want to make a contribution to that conversation;
i.e., you will need to design and undertake some research (albeit that
the specific design of that research will be shaped by a range of
factors beyond your research question, as shown
in [#fig:huff51].

![Design decisions connecting research purpose and outcomes [@huff_2009_designingresearchpublication p. 86]](images/Huff-2009-fig5.1.svg){#fig:huff51}


## The general structure of the course

This course is divided into five major topics: *You and qualitative
research*, *Qualitative methods*, *Collecting qualitative data*,
*Analysing qualitative data*, and *Presenting your results*. However,
to maximise the amount of time you can spend practising with the tools
and techniques of qualitative methods, the course is structured around
three concurrent streams of activity:.

1. Skill in using the various techniques and tools of qualitative
   research.
2. Knowledge of qualitative research methods in general.
3. Knowledge of the position of qualitative research methods in your
   chosen academic conversation.

*Work stream 1* activities will largely take place inside the class;
e.g., practising doing interviews, but will also require work outside
of the too, such as developing an interview schedule.

Activities relating to *Work stream 2* mainly be addressed through tasks
regarding specific readings (e.g., from the textbooks).

In contrast, *work stream 3* activities will be based around you
identifying and reading around your specific research conversation, and bringing those insights into the classroom to share with your colleagues.

You will do most of the tasks around work streams 2 and 3 outside of
the classroom.

## Workflow pattern

The pattern of your work in this class, is generally:

1. Complete the tasks to prepare for the classwork
3. Do exercises in class
4. Write your weekly learning journal
5. Review the learning journals that you have been allocated

