# Week-by-week in detail

As noted elsewhere in this course guide, the average student should expect to spend about 20 hours each week doing work related to this course (including class time). To guide your efforts, I have indicated the approximate time you should spend on each of the tasks described in the detailed week-by-week breakdown.  (6&delta;)



## Week 1: You and qualitative research{#W1-details}

Having successfully completed the course BUSINESS 710 (Research
Design), you already know a lot about doing research, and so many of
topics of this week will already be familiar to you. However, in this week 


- Review "Choosing an academic home"
  [@huff_2009_designingresearchpublication]

	- *Describe* the academic conversation to which you wish to make a
	  contribution.

	- Given the characteristics of your choose academic conversation,
      *discuss* the extent to which there are well understood patterns
      of research; i.e., is it the case that you are "in the midst of
      a conversation where many choices have been previously debated
      and an overarching agenda has been established"
      [@huff_2009_designingresearchpublication p. 87]. What are the
      implications of those patterns for the choice of methods in your
      conversation?

- Read "Part I" and "Part 2" of Myers
  [-@myers_2013_qualitativeresearchbusiness p. 3--56]

	- *Summarise* the 'big idea' that underpins Chapter 2 of the
	  textbook. What parallels, if any, are there with other books and
	  articles you have read?
  
	- *Compare and contrast* the role of philosophic assumptions as
	  presented by Myers [-@myers_2013_qualitativeresearchbusiness] and
	  Huff [-@huff_2009_designingresearchpublication].

- Read "Guiding Principles for conducting research with human
  participants" [@theuniversityofauckland_2013_guidingprinciplesconducting].

	The University of Auckland has a processes and policies around
	conducting research. One of the most important documents is
	entitled "Guiding principles for conducting research with human
	participants." A copy of these guidelines can be found on the
	University's website at:
	https://www.auckland.ac.nz/en/about/research/re-ethics/re-uahpec.html.


	- Show the relationship between Myers
	[-@myers_2013_qualitativeresearchbusiness], Huff
	[-@huff_2009_designingresearchpublication] and the Univesity's
	"Guiding principles ..." with regard to ethics in conducting
	research.



## Collecting qualitative data (week 2) {W2-details}
---------------------------

- Read "Part IV" of Myers
  [-@myers_2013_qualitativeresearchbusiness p. 117--162]

### Interviewing ###

### Focus groups ###

### Participant observation ###

### Archival research ###



## Qualitative reserach methods (week 2)  {#W3-details}

For Myers a qualitiative research methods is "a strategy of enquiry
... of finding empirical data about the (social) world"
[-@myers_2013_qualitativeresearchbusiness p. 4]. In a practical sense,
a qualititative research method might drawn a variety of approaches to
collecting and analysing qualitative data; for example, a case study
might use interviews and observations, or maybe archival research,
with the data being analysed through themematic analysis.

That does not mean the research necessarily has a free reign to mix
and match from all of the data collection and analysis techniques.
Depending on the stricutures of any particular research method, only
some combinations might be appropriate.

- Read "Part III" of Myers
  [-@myers_2013_qualitativeresearchbusiness p. 57--116]

### Action Research ### ###

### Case studies ###

### Ethnography and observations ###

### Grounded theory ###






## Analysing qualitative data (weeks 4)  {#W4-details}

- Read "Part V" of Myers
  [-@myers_2013_qualitativeresearchbusiness p. 163--220]

### Hermeneutics ###

### Semiotics ###

### Narrative analysis ###




## Analysing qualitative data (weeks 5) {#W5-details}

### Content analysis ###

### Themematic analysis ###

### Discourse analysis ###



## Presenting your results (week 6) {#W6-details}

- Read "Part VI" of Myers
  [-@myers_2013_qualitativeresearchbusiness p. 221--246]

### Writing up qualitative research ###

### Presenting specific types of analysis ###


- Presenting thematic analysis

	e.g., the Gioia method [@gioia_2013_seekingqualitativerigor]

- Presenting fieldnotes; 

	Jarzabkowski et al.** [@jarzabkowski_2015_conductingglobalteambased]

