# Week five {#w5-details}

The final research methods we are looking at is grounded theory. When
I last looked on Google Scholar, the seminal work by Glaser and Straus
[-@glaser_1967_discoverygroundedtheory] had nearly 10,000 citation.
So, this is a very important strategy in qualitative research. That
said, the ideas from grounded theory around the analysis of
qualitative data are perhaps even more important.

Given that, this week we will focus on grounded theory and
practice more coding.

## First class {-}

### Overview {-}

Our first class of the week will focus on (a) bringing you speed on
'classical' grounded theory in its many forms.

### Class plan {-}

* Urquhart argues that the choice between "Glaserian or Straussin
  [grounded theory] --- depends on individual researchers and their
  preferences" [@urquhart_2017_groundedtheoryqualitative]. Which is
  your preference?
  
* How has grounded theory been used in your field?

* Thinking back to the paper by Smets and his colleagues
  [@smets_2015_reinsurancetradinglloyd], what type of coding do you
  now think they did?

* Looking back, what type of coding did you _actually_ do when you first
  tried thematic analysis of Appendix \@ref(engineering) (e.g.,
  bottom-up, top-down, middle-range, or thematic)?

* Regarding your open coding of Appendix \@ref(engineering), which of your
  codes are descriptive and which are analytical? 

* What is your theory of academic work-life balance?

### Prep and tasks {-}

1. Read Chapter 9 of Myers [-@myers_2013_qualitativeresearchbusiness
  p. 209--220] to get an overview on Grounded Theory --- 30
  minutes.

2. For the leading two or three journals in your own field, say,
   entrepreneurship, do a search and see how grounded theory has been
   used. Be prepared to report back on your findings --- 30 minutes

3. Visit the SAGE Research methods website: read chapters 1--3 and
   chapter 5 of [Urquhart's
   book]([http://methods.sagepub.com/book/grounded-theory-for-qualitative-research) [@urquhart_2017_groundedtheoryqualitative] on
   grounded theory --- 210 minutes.
   
   
4. Review the coding by Smets and his colleagues, how would you
   describe it now (bottom-up, top-down, middle-range, or thematic)?
   --- 30 minutes.

5. Using whichever QDA tool you feel most comfortable with, go back to
   Appendix \@ref(engineering) and try open coding it --- 30
   minutes.

6. Return to the 'discussion'
   on
   [StackExchange Academia on work-life balance re teaching and research](https://academia.stackexchange.com/questions/89362/how-do-academics-with-teaching-responsibilities-etc-find-the-time-to-do-resear).
   Apply the stages of open, selective, and theoretical coding to it?
   Start with a general research problem. Draw some diagrams and make
   a few theoretical notes. Generate some research questions based on
   your theoretical coding? Can you come up with a theory about
   academics and work-life balance? --- 120 minutes.
   

## Second class {-}

### Overview {-}

We now move on to what is often called the Gioia method; a more
contemporary expression of many of the ideas of grounded theory. This
approach to coding (and reporting results) has become immensely popular
of late.

### Class plan {-}

* How is the Gioia method related to grounded theory?

* To what extent do the exemplars of the Gioia method that you have
  read, achieve rigour?
  
* To what extent do the exemplars of the Gioia method that you have
  read, achieve transferability?

* What lessons do you take away about presenting qualitative research, in general?

* What lessons do you take away about presenting qualitative research,
  _vis-รก-vis_ your work on academic work-life balance? (To be
  effective, you will need to show your 'Gioia' write-up)



### Prep and tasks {-}

1. Read the paper by Gioia and his co-authors on the 'Gioia method'
   [@gioia_2013_seekingqualitativerigor] --- 30 minutes.

2. Draw a concept map linking the key tenets of the Gioia method to
   grounded theory? --- 15 minutes.
   
3. Review the article by Gioia and Thomas
   [-@gioia_1996_identityimageissuea]---it one of Gioia's exemplars
   and was published in one of the leading _quantitative_ journals,
   which is quite an achievement for a piece of qualitative research.
   How closely do Gioia and Thomas follow the Gioia method? --- 45
   minutes. 
   
   If you are not familiar with the idea of sensemaking, there is a
   nice/short literature review by Brown et al.
   [@brown_2015_makingsensesensemaking].
   
3. The paper by Anand et al.
   [@anand_2007_knowledgebasedinnovationemergence], is also one of the
   exemplars cited by Gioia et al,
   [-@gioia_2013_seekingqualitativerigor]. Review the paper and
   evaluate how close it follows Gioia's method --- 45 minutes.
   
4. For the exemplars you have read assess their transferability. Do
   you agree with the stance taken by Gioia et al
   [-@gioia_2013_seekingqualitativerigor]? --- 30 minutes.

   
4. For a third time, return to the 'discussion' on StackExchange
   Academia on work-life balance re teaching and research
   (https://academia.stackexchange.com/questions/89362/how-do-academics-with-teaching-responsibilities-etc-find-the-time-to-do-researc),
   which you should be rather familiar now, and apply the Gioia
   method. Write-up your results following the advice of Gioia et al.
   [-@gioia_2013_seekingqualitativerigor] --- 120 minutes.
   

## End of week {-}

With the week's classes behind you, it is time to do your learning
journal (60 minutes) and then review the learning journals of your
peers (60 minutes).
