# Week six {#w6-details}

## First class {-}

### Overview {-}

As we head into the 'home stretch' of the course, and the topic of
'Presenting your research' it is tempting to think that we have come
to the end of the research process; the data has been collected,
analysed, and all that is left is to present our findings. Alas, it is
often the case that in writing-up our work, we find that we need new
literature, extra data, more analysis. Writing up can often be the
trigger for further iterations through the research cycle. It is not
unusual, having submitted a piece of work that we thought was
'perfectly fine', to have reviewers ask for "an additional comparative
case", or for the inclusion of a particular piece of literature that
then means additional interviews have to be done. It is also the case
that there are few researchers who haven't been told "There are two
papers here", or "Your research question needs some work", resulting
in almost new papers being written.

So, writing-up is not always the end.

Even so, as your summative learning journal looms large on the
horizon, the plan for this week is relatively light to allow you to
focus on that task.

### Class plan {-}

* Reflecting on the readings by Gioia and Jarzabkowski, what is their
  impact on how you think about qualitative research design?

* What tools and techniques from the course will you use in completing
  your summative learning journal?

* Compare and contrast the 'specialist' recommendations you found on
  writing up with that from Myers
  [-@myers_2013_qualitativeresearchbusiness p. 221--250].
  
* How does that specialist advice differ to that which your colleagues found (regardless of the choice of method)?

* What lessons from Myers [-@myers_2013_qualitativeresearchbusiness
   p. 221--250] will you bring through to your summative learning
   journal?

* What question do you have about your summative learning?

* 'Pair and share' the outlines of your summative learning journal.
  What actionable feedback can you give to help your colleagues?


### Prep and tasks {-}

1. Read "Part IV" of Myers [-@myers_2013_qualitativeresearchbusiness
   p. 221--250] --- 30 minutes.
   
   - *List* two or three ideas from this reading, that you will apply to
     your summative learning journal --- 10 minutes.
	 
2. *Discuss* the idea that, "As used in this course, a summative
   learning journal is a form of auto-ethnography". --- 30 minutes.
   
3. *Discuss* the question, "Does an auto-ethnographic study require
   approval from the University of Auckland Human Participants Ethics
   Committee?" --- 20 minutes.

4. There are many papers on presenting your research. These often
   spill over into how you should collect and analyse your data. You
   have already read one by Gioia et al.
   [-@gioia_2013_seekingqualitativerigor]. Review the paper by
   Jarazabkowski and her colleagues on producing persausive findings
   [@jarzabkowski_2014_producingpersuasivefindings]. How do papers
   like these shape how you intend to present your summative learning
   journal ? --- 90 minutes.
   
5. There are many specialised texts on particular reserch methods,
   e.g., action research, or thematic analysis. These texts often
   contain a chapter on 'writing up'. For a method that you think you
   are likely to use in your own research, find an appropriate chapter
   on the SAGE research methods website, and summarise the key points.
   
6. Review both Daudelin
   [-@daudelin_1996_learningexperiencereflection]and Payne and Payne
   [-@payne_2004_reflexivity] from Week 1. What are you trying to
   achieve in your summative learning journal? This could be the
   opening paragraph to your summative learning journal --- 30
   minutes.

7. Write a detailed *draft* unless you are feeling
   ambitious) of your summative learning journal and bring it to class
   --- 240 minutes.
   
### Post class reflection

With the first class of the week behind you, it is time for you to reflect on what
you have learnt and write-up your learning journal (Section
\@ref(ass1) &dash; 90 minutes). You can then do your review your allocated learning
journals of you  peers (Section \@ref(ass1) &dash; 60 minutes).


## Second class {-}

### Overview {-}

This class is dedicated to your summative learning journals. If you have no question or concerns, you can consider spending the time working on your final piece of work.

### Class plan {-}

* Foreshadowing your summative learning journals, what are your big takeaways?

* Wrapping it up

* Class party? (Class lunch?)

### Prep and tasks {-}

1. Do more revisions/iterations on your summative learning journal
   --- 360 minutes.


## End of the course {-}

The course is pretty much over now. All you need to do now is polish
up your summative learning journal (Section \@ref(ass3)) --- 120
minutes.
