# (APPENDIX) Appendix {-}

# Postgraduate profile {#profile}

## Preamble
The University of Auckland has developed a collection of Graduate
Profiles for students in postgraduate level programmes that expresses
an aspiration for its graduates through a set of university-wide
attributes and values which it considers to be attainable by graduates
of a leading research university. They communicate to current and
potential students and faculty, employers, the community, and other
academic institutions the qualities that The University of Auckland
seeks to impart to, or foster in, its graduates. The Graduate Profiles
that have been developed are for: (i) Postgraduate Coursework
Graduates; (ii) Postgraduate Research Graduates (masters level or
equivalent); and (iii) Doctoral Graduates.

The University of Auckland is committed to provide an educational
experience of the highest standards to its students. In addition, The
University of Auckland recognises the needs of a diverse and
multi-cultural student population, including its special
responsibility under Te Tiriti o Waitangi / The Treaty of Waitangi.

The implementation of the Graduate Profiles rests with the faculties,
departments, and other teaching and learning support divisions of the
University, which may develop more specific profiles that are suitable
for their subject fields and/or student population. As the student
learning environment changes, the Graduate Profiles will be reviewed.

## Description
A Postgraduate Research Graduate (ie, masters level or equivalent)
will demonstrate welldeveloped skills in the definition, management,
and communication of research in a specialist area. On completing
their studies at a satisfactory level, Postgraduate Research Graduates
will have attained a core set of attributes and values that provide a
platform to allow them: (i) to undertake advanced and original
research at the doctoral level in their chosen subject field; (ii) to
continue developing personally and professionally in their careers;
and (iii) to make potentially innovative, and important contributions
to the communities and societies in which they reside. The University
of Auckland expects its Postgraduate Research Graduates to obtain the
following attributes and values:

### Specialist knowledge
1. A mastery of a body of knowledge, including a high level
   understanding of conceptual and theoretical elements, in the field of
   study.
2. An understanding and appreciation of current issues and debates in
   the field of study.
3. An understanding and appreciation of the philosophical bases,
   methodologies and characteristics of scholarship, research, and
   creative work.
4. An understanding of the relevance and value of their contribution
   to the local and global communities’ knowledge of fact, theory,
   and/or mastery of practice

### Effective communication
1. A capacity to communicate ideas effectively in suitable formats to
   a range of audiences inside the field of study or discipline and to
   the wider community.
2. An ability to communicate effectively using written and spoken
   English and/or Māori, and where appropriate, other languages.

### General intellectual skills and capacities
1. A capacity for critical, conceptual, and reflective thinking.
2. A capacity to locate, contextualise, critically evaluate,
   synthesise, and use information effectively.
3. An ability to analyse information, where relevant, using
   appropriate tools, technologies, and methods.
4. A capacity for critical appraisal of relevant scholarly literature.
5. An ability to initiate, design, conduct, sustain, and report
   research.
6. A willingness to seek continuous improvement in research skills and
   quality of research.
7. Interdisciplinary perspectives.
8. The self-awareness to identify one’s professional, personal, and
   research skills, the ability to market these appropriately in the
   employment market.
9. An understanding of career and professional development strategies.
10. The ability to work independently, as well as collaboratively and
    effectively with others, as appropriate.

### Independence, creativity and learning
1. An intellectual openness and curiosity.
2. A capacity for creativity and originality.
3. An ability to identify, define, analyse, and solve problems in a
   flexible manner and the skill to adapt innovatively to changing
   environments and outcomes.
4. An appreciation for ideas, discovery, and learning.
5. Self discipline and an ability to plan and achieve goals (personal
   and professional), including career advancement and identifying
   appropriate opportunities in the chosen field.

### 5. Ethical and social understanding
1. Personal, professional and intellectual integrity, and respect for
   the ethics of research and scholarly activity.
2. An awareness of local and global dimensions of intellectual,
   political, and economic activities.
3. An appreciation of human and cultural diversity and respect for the
   values of individuals and different cultural groups.
4. An awareness of the implications and potential of their research in
   terms of intellectual property and commercialisation.
