# Course design {#course-design}

A lot of thought went into the design of the course to make it
something good.


My teaching and your learning
-----------------------------

My approach to teaching is shaped by three concerns. First, "What is it
that I want you to be able to do at the end of the course?" What
skills, knowledge, and attitudes am I seeking to engender---what do I
hope you will have learn? This is articulated through the learning
outcomes for the course.

When I talk of learning, I following Terry Doyle, in that:

> Learning is the ability to use information after a significant
> period of disuse 
>
> and 
>
> It is the ability to use the information to solve problems in a
> context different (if only slightly) from the context in which the
> information was originally learnt.

In a nutshell, I want you to be able apply what you have learnt here to
your own (future) research project(s).

My second concern is "What is the best use of our time together?".
Implicitly, this also addresses the use of your individual study
time). The result of this concern is a preference for a 'flipped'
classroom, where delivery of the content of the course takes place
outside of the classroom, and where time in the classroom is spent
working with that content to refining your understanding.

Finally, "What are effective ways of learning?" As noted earlier,
praticing something is one way to become more accomplished at it. That
process can be accelerated by engaging in explicit reflection of ones
practice(s), on your 'doings' and 'sayings'
[@schatzki_2001_practiceturncontemporary].




