# The historical roots of engineering {#engineering}

The purpose of this section is to provide an overview of the
historical context from which a variety of engineering disciplines
have emerged. The compilation of any history of engineering requires
the researcher to make choices as to what is, and what is not,
included. This applies as much to the selection of which disciplines
of engineering to review, as to the events and pressures that shaped
the profession. Consequently, this history does not address the role
of engineers in, for instance, nuclear engineering or
microelectronics. Instead, the disciplines with greater relevance to
Arlington are emphasised. Such editing is a necessity of space and
time.

The etymology of engineer is found in the notion of one who does
something ingenious (Oxford University Press, 1989); that is, "a
person possessing an innovative mind and skilful hands", an
"ingeniator" (Harms, 2004, p. 3). Though some engineers, trace their
heritage as ingeniators to prehistoric tool making (Harms, 2004), it
is during the Renaissance (circa 1300–1699), that the beginning of
modern engineering becomes more apparent (Garrison, 1998). During that
time, engineers adopted mathematical methods to tackle a variety of
problems such as statics (the mechanics of rigid bodies), ballistics,
and topographical surveying. They drew on systematic empirical
investigation and adopted scientific language (Armytage, 1976;
Garrison, 1998; Norrie, 1956). The use of mathematical methods,
together with the adoption of scientific method marks, the transition
of engineering from an occupation based on artisanship towards one
more resembling the modern profession. During the seventeenth and
eighteen centuries, engineers progressively formalised their training.
Until about 1760, most engineering was associated with governmental
works including "the constructional requirements of … dockyards and
harbours, of land fortifications and of roads built for the better
travel of troops rather than for civil needs" (Norrie, 1956, p. 6).
The need for such military engineering led to the establishment of the
French corps of engineers. The formation of the Corps de Ponts et
Chaussées (of bridges and roads) in 1716 was followed by the founding
of an engineering school, L'École des Ponts et Chaussées in 1747
(Armytage, 1976). The creation of this school was followed a by number
of others and it became the model for L'École Polytechnique both in
and beyond France (Garrison, 1998). The academic leadership of French
engineering led to the publication of the first civil engineering
reference books. Two of the most notable are Science des Ingénieurs in
1729 and Architecture Hydraulique in 1737. The first of these were in
print for over one-hundred years (Norrie, 1956).

Engineers were also involved in the formation of professional
societies. In England, a meeting in 1660 to discuss "the founding of a
colledge for the promoting of Physico-Mathematicall Experimentall
Learning" culminated in the creation of the Royal Society in 1662
(Armytage, 1976, p. 77). During the eighteenth century, the meaning of
engineer grew to encompass those undertaking civil works. The
applications of civil engineering included the construction of canals,
bridges, and wharves (Garrison, 1998). John Smeaton, the builder of
the Eddystone Lighthouse, founded the Society for Civil Engineers
in 1771. The Smeatonian Society, as it was sometimes called, the first
of its kind, was an expression of the professional interests of its
members in civil engineering (Norrie, 1956). It led to the
establishment of the Institution of Civil Engineers in 1818 and, in
turn, to the first English school of engineering in 1827 at King's
College in London (Norrie, 1956). In America, civil engineers created
their professional society, the American Society of Civil Engineers
and Architects, in 1852.

Aside from civil engineering, other engineering specialisations arose.
Mechanical engineers were at the forefront of the industrial
revolution (Garrison, 1998). They brought their knowledge and skill to
improving waterpower and to the development of steam power. Alongside
these advances, engineers created new processes for manufacturing iron
and steel. Mining engineers, in expediting the supply of coal and iron
ore, facilitated this. Mass-production of iron and steel, together
with steam power, enabled the creation of much of the of
transportation infrastructure in the form of steamships and railways
(Garrison, 1998). With the expansion of the railways came greater
demand for bridges, often constructed from the new mass-produced iron
and steel. The rise of the steamship also produced the new engineering
discipline of naval engineering (Armytage, 1976). These new engineers
drew on the practices of other engineering disciplines. For example,
similar to bridge designers, they utilised physical models to predict
more accurately the performance of their designs using a combination
of mathematics, experimentation, and intuition.

In Germany, a new breed of engineers, chemical engineers, were
advancing industrial chemistry (Armytage, 1976; Harms, 2004). The
variety of products produced by chemical engineering include dyes,
drugs, explosives, acids, organic chemicals and other "fine chemicals"
(Garrison, 1998). Nevertheless, engineers were not concerned solely
with commerce; epidemiological studies in the mid-1800s highlighted
the necessity of potable water supplies and separate sewage disposal
resulting in the emergence of sanitary and hydraulic engineers. The
first electrical engineers also appeared during this period. The work
of Michael Faraday, André-Marie Ampere, and others, led to the
emergence, and widespread distribution, of the electrical industry
(Garrison, 1998). Innovations such as electric lighting, the
telegraph, and the accompanying electrification of cities changed the
way people worked and lived. Power for the new electrical networks
came from steam turbines or from waterpower. For example, in 1893,
Westinghouse won the contract to build generators powered by the water
from Niagara Falls. Such large-scale projects necessitated the effort
of many engineers across many specialisations, working together with
those contracted for construction.

During the nineteenth century, there were significant changes in the
way that construction was undertaken. Until that time, casual labour
was utilised to undertake public works. However, those who funded such
works increasingly sought "binding commitments to cover all the risks
and responsibilities of construction" (Norrie, 1956, p. 89) and
guarantees against contractors failing to complete the contracted
work. As a result, contractors changed from being simple suppliers of
organised labour to "men of greater calibre to carry the executive
burden" (Norrie, 1956, p. 89). As British engineers and navvies were
employed overseas, the new contracting methods spread to France and
beyond. Contracting for construction work developed into a
project-based business. Even in the early days the "contractor's
assets could generally be easily realized and a business be wound up
without undue loss, and many with good profits took advantage of this"
(Norrie, 1956, p. 97). One result of the move to contracting was that
for any project there were often three parties involved: the client,
who would fund the project; the engineer who would do the design work;
and the contractor, who would actually build the project, often under
the partial supervision of the engineer. Such tripartite arrangements
predominate even to this day. The traditional approach is for the
client to select a designer (an engineering firm or an architectural
firm) and a contractor (who will actual build what is designed)
through a process of competitive bidding (Beard, Loulakis, & Wundram,
2001). If multiple forms of design work are required, such as
structural engineering and fire engineering, then a lead design firm
may tender for the work in conjunction with other, subcontracted,
firms. Similarly, if the construction of the project requires multiple
contractors, a lead contractor will engage sub-contractors and
sub-trades as necessary. This process is known as the design-bid-build
project delivery method. The twentieth century saw the rise of new
forms of engineering, including petroleum engineering, aeronautical or
aerospace engineering, electronic engineering, biomedical engineering,
and other specialties. Classification of engineers, such as mechanical
or civil engineers, is illustrative of how engineering is associated
with the classes of devices they produce (Harms, 2004). For the
purpose of this thesis, the major categorisations of contemporary
engineering are civil, mechanical, electrical, structural, water,
material, surveying, transportation, urban, and industrial. 
